redis:
  host: localhost
  port: 6379

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: nhan
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

